config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # login_stuff
  match '/auth/:provider/callback' => 'sessions#create', via: [:get, :post]
  match '/logout' => 'sessions#destroy', via: [:get, :post]

  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  # home stuff
  root 'application#welcome'

  # model stuff
  resources :users do
    resources :days, only: [:show, :new]
  end
  resources :accomplishments

  # days routes
  resources :days, only: [:index, :show]
  get '/today' => 'days#today'

  get '/weekdays/:day' => 'accomplishments#day_of_week_index', as: 'day_of_week'
  get '/weekdays/:day/accomplishments/new' => 'accomplishments#new', as: 'new_weekday_accomplishment'

  get '/users/with-most-unique-accomplishments/:amount' => 'users#with_most_unique_accomplishments', as: 'most_accomplishments'

  get '/users/with-bussiest-week/:amount' => 'users#with_bussiest_week', as: 'bussiest_week'

  get '/leaderboard' => 'users#leaderboard'

end

app/models/user.rb
class User < ApplicationRecord
  has_many :identities

  validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  validates_uniqueness_of :email, {case_sensitive: false}
  validates_presence_of :email, :first_name, :last_name

  has_secure_password validations: false
  validates :password, presence: true, unless: :skip_password_validation
  validates :password, confirmation: true
  validates :password_confirmation, presence: true, unless: :skip_password_validation

  attr_accessor :skip_password_validation

  has_many :days
  has_many :day_accomplishments, through: :days
  has_many :accomplishments, through: :day_accomplishments



  def self.find_or_create_by_auth(auth_hash)
    @user = self.where(email: auth_hash[:info][:email]).first_or_initialize.tap do |u|
      u.first_name = first_name_from_full_name(auth_hash[:info][:name])
      u.last_name = last_name_from_full_name(auth_hash[:info][:name])
      u.email = auth_hash[:info][:email]
      u.skip_password_validation = true
      u.days.build(name: 'Sunday')
      u.days.build(name: 'Monday')
      u.days.build(name: 'Tuesday')
      u.days.build(name: 'Wednesday')
      u.days.build(name: 'Thursday')
      u.days.build(name: 'Friday')
      u.days.build(name: 'Saturday')
      u.save
    end
  end

  def self.create_from_signup(signup_params)
    @user = User.new(signup_params)
    if @user.save
      @user.days.create(name: 'Sunday')
      @user.days.create(name: 'Monday')
      @user.days.create(name: 'Tuesday')
      @user.days.create(name: 'Wednesday')
      @user.days.create(name: 'Thursday')
      @user.days.create(name: 'Friday')
      @user.days.create(name: 'Saturday')
    end
    @user
  end

  def self.first_name_from_full_name(full_name)
    full_name.split(' ')[0..-2].join(' ')
  end

  def self.last_name_from_full_name(full_name)
    full_name.split(' ')[-1]
  end

  def full_name
    self.first_name + ' ' + self.last_name
  end

  def self.with_most_unique_accomplishments(amount = 5)
    self.joins(:accomplishments).group(:id).order(Arel.sql('count(accomplishments.id) desc')).limit(amount)
  end

  def self.with_bussiest_week(amount = 5)
    self.joins(:day_accomplishments).group(:id).order(Arel.sql('count(day_accomplishments.id) desc')).limit(amount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_because_logged_in, only: [:new]
  before_action :require_login, only: [:edit]
  before_action :set_user, only: [:edit, :update, :destroy]


  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create_from_signup(signup_params)
    if @user.save
      self.current_user = @user
      flash[:welcome] = 'Welcome! You made an account!'
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    flash[:showing] = ""
    @user = User.includes(days: :accomplishments).find(params[:id])
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @user, include: ['days'] }
    end
  end

  def edit
  end

  def update
    @user.skip_password_validation = true
    @user.update(edit_params)
    if @user.save
      flash[:updated] = 'Update succesful.'
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user.identities.each do |i|
      i.destroy
    end
    @user.destroy
    flash[:deleted] = 'You have successfully deleted your account'
    session.clear
    redirect_to root_path
  end

  def with_most_unique_accomplishments
    @users = User.with_most_unique_accomplishments(params[:amount])
    flash[:showing] = 'Showing Users with most unique accomplishments'
    render :index
  end

  def with_bussiest_week
    @users = User.with_bussiest_week(params[:amount])
    flash[:showing] = 'Showing Users with the bussiest week.'
    render :index
  end

  def leaderboard
    @top_user = User.joins(:day_accomplishments).group(:id).order('count(day_accomplishments.id) desc').limit(1)[0]
  end

  private

  def edit_params
    params.require(:user).permit(:first_name, :last_name, :email)
  end

  def signup_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Edit Profile</h1>
<%= form_for @user do |f| %>
  First Name:
  <br>
  <%= f.text_field :first_name %>
  <br>
  Last Name:
  <br>
  <%= f.text_field :last_name %>
  <br>
  Email Address:
  <br>
  <%= f.email_field :email %>
  <br>
  <%= f.submit 'Update!' %>
<% end %>

<div>
  Or,
</div>

<%= link_to 'Delete Profile', user_path(@user), method: :delete %>

app/views/users/index.html.erb
<h1>Users</h1>

<% @users.each do |user| %>
  <div class="list-style">
    <%= link_to "#{user.first_name} #{user.last_name}", user %>
    <%= link_to "Show Accomplishments", user, {class: "js-show"} %>
  </div>
  <div id="js-user-info-<%= user.id %>">

  </div>
<% end %>

<%= javascript_include_tag "userShow" %>

app/views/users/leaderboard.html.erb
<h1>Top User</h1>
<% if @top_user %>
    <div>
        Name: <%= @top_user.full_name %>
        <br>
        Amount of Accomplishments: <%= @top_user.accomplishments.count %>
        <br>
    </div>
<% end %>

app/views/users/new.html.erb
<h1>Signup</h1>

<%= link_to 'Sign up with Google', '/auth/google_oauth2' %>
<br>
<%= link_to 'Sign up with Github', '/auth/github' %>

<h3>Or,</h3>

<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div class="error_explanation">
      <h6><%= pluralize(@user.errors.count, "error") %> must be fixed before this accomplishment can be saved.</h6>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  First Name:
  <br>
  <%= f.text_field :first_name %>
  <br>
  Last Name:
  <br>
  <%= f.text_field :last_name %>
  <br>
  Email Address:
  <br>
  <%= f.email_field :email %>
  <br>
  Password:
  <br>
  <%= f.password_field :password %>
  <br>
  Password Confirmation:
  <br>
  <%= f.password_field :password_confirmation %>
  <br>
  <br>
  <%= f.submit 'Sign Up!' %>
<% end %>

app/views/users/show.html.erb
<h6>Name: <%= @user.first_name %> <%= @user.last_name %> || Email Address: <%= @user.email %></h6>
<% if @user == current_user %>
  <%= link_to 'Edit Profile', edit_user_path(current_user) %>
  <h1>Your Week</h1>
<% else %>
  <h1><%= @user.first_name %> <%= @user.last_name %>'s Week</h1>
<% end %>




<% @user.days.each do |day| %>
  <div class="list-style">
    <div class="">
      <%= link_to day.name, user_day_path(@user.id, day) %>
    </div>
    <% if logged_in? %>
    <div class="smaller">
      <%= link_to 'Add', new_weekday_accomplishment_path(day.name.downcase)  %>
    </div>
    <% end %>
  </div>

  <div class="width-fix">
    <ul>
      <% day.accomplishments.each do |acc| %>
        <li class="">
          <div class ="accomplishment-list-style">
            <div class="">
              <%= link_to acc.title, accomplishment_path(acc) %>
            </div>

            <div class="">
              <%= acc.human_time %>
              |&#9829;|
              <%= link_to 'Details', accomplishment_path(acc) %>
              <% if current_user == @user %>
              |
              <%= link_to 'Edit', edit_accomplishment_path(acc) %>
              |
              <%= link_to 'Remove', accomplishment_path(acc), method: :delete %>
              <% end %>

            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>