config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # login_stuff
  match '/auth/:provider/callback' => 'sessions#create', via: [:get, :post]
  match '/logout' => 'sessions#destroy', via: [:get, :post]

  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  # home stuff
  root 'application#welcome'

  # model stuff
  resources :users do
    resources :days, only: [:show, :new]
  end
  resources :accomplishments

  # days routes
  resources :days, only: [:index, :show]
  get '/today' => 'days#today'

  get '/weekdays/:day' => 'accomplishments#day_of_week_index', as: 'day_of_week'
  get '/weekdays/:day/accomplishments/new' => 'accomplishments#new', as: 'new_weekday_accomplishment'

  get '/users/with-most-unique-accomplishments/:amount' => 'users#with_most_unique_accomplishments', as: 'most_accomplishments'

  get '/users/with-bussiest-week/:amount' => 'users#with_bussiest_week', as: 'bussiest_week'

  get '/leaderboard' => 'users#leaderboard'

end

app/models/day.rb
class Day < ApplicationRecord
  belongs_to :user
  has_many :day_accomplishments
  has_many :accomplishments, through: :day_accomplishments


  validates_uniqueness_of :name, scope: :user_id

  def user_unique_link
    self.user.full_name + "\'s " + self.name
  end

  def accomplishments_by_time
    self.accomplishments.order(Arel.sql('time(date_time) asc'))
  end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController

  before_action :require_login, only: [:today]
  
  def index
    @days_of_the_week = DateTime::DAYNAMES
  end

  def show
    if params[:user_id]
      @day = User.find(params[:user_id]).days.find(params[:id])
    else
      @day = Day.find(params[:id])
    end
  end

  def today
    @day = current_user.days.find_by(name: Time.zone.now.strftime('%A'))
    render :show
  end
end

app/helpers/days_helper.rb
module DaysHelper
end

app/views/days/day_of_week_index.html.erb
<h1>All User's <%= @name_of_day %>s</h1>

<% @days.each do |week_day| %>
  <div class="list-style">
    <%= @name_of_day %> for <%= link_to(week_day.user.full_name, day_path(week_day)) %></div>
<% end %>

app/views/days/index.html.erb
<h3>See Accopmlishments by</h3>
<h1>Day of the Week</h1>
<!-- links to all users days by day of week -->

<% @days_of_the_week.each do |day_str| %>
  <div class="list-style">
    <%= link_to day_str, day_of_week_path(day_str) %>
  </div>
<% end %>

app/views/days/show.html.erb
<% if @day.user == current_user %>
  <h2>Your <%= @day.name %></h2>
<% else %>
  <h2><%= @day.name %></h2>
<% end %>
<div class="list-style">
  <%= link_to 'Add something.', new_weekday_accomplishment_path(@day.name.downcase) %>
</div>

<% if @day.accomplishments.empty? %>
  <div class="list-style">
    Nothing tracked yet...
  </div>
  <br>
<% else %>

  <% @day.accomplishments_by_time.each do |acc| %>
    <div class="list-style">
      <div><%= link_to acc.title, acc %></div>
      <div><%= acc.time_of_accompmlishment %></div>
    </div>
    <div class="effect">
      <%= acc.effect %>
    </div>
    <div class="doing-on">
      Every: <% acc.days.each do |day_obj| %>
        |<%= link_to day_obj.name, day_path(day_obj) %>|
      <% end %>
      <div>
        <%= link_to  "Info", acc, {class: "js-show"} %>
      </div>
    </div>
    <div id="js-accomplishment-info-<%= acc.id %>">

    </div>
  <% end %>
<% end %>

<%= javascript_include_tag "accomplishmentShow" %>