config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # login_stuff
  match '/auth/:provider/callback' => 'sessions#create', via: [:get, :post]
  match '/logout' => 'sessions#destroy', via: [:get, :post]

  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  # home stuff
  root 'application#welcome'

  # model stuff
  resources :users do
    resources :days, only: [:show, :new]
  end
  resources :accomplishments

  # days routes
  resources :days, only: [:index, :show]
  get '/today' => 'days#today'

  get '/weekdays/:day' => 'accomplishments#day_of_week_index', as: 'day_of_week'
  get '/weekdays/:day/accomplishments/new' => 'accomplishments#new', as: 'new_weekday_accomplishment'

  get '/users/with-most-unique-accomplishments/:amount' => 'users#with_most_unique_accomplishments', as: 'most_accomplishments'

  get '/users/with-bussiest-week/:amount' => 'users#with_bussiest_week', as: 'bussiest_week'

  get '/leaderboard' => 'users#leaderboard'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BuiltWith7</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta content="width=device-width, initial-scale=1" name="viewport">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.4.7/webfont.js" type="text/javascript"></script>
    <script type="text/javascript">WebFont.load({  google: {    families: ["Bitter:400,700,400italic"]  }});</script>

  </head>

  <body>
    <div data-collapse="none" data-animation="default" data-duration="400" class="navbar w-nav">
      <div class="container w-container">
        <a href="/" class="brand w-nav-brand">
          <div class="text-block">Habit Builder</div>
        </a>
        <% if logged_in? %>
          <%= link_to 'Log Out', logout_path, {class: "nav-link w-nav-link"} %>
        <% end %>
        <nav role="navigation" class="nav-menu-2 w-nav-menu">
          <% if logged_in? %>
            <%= link_to 'Add Accomplishment', new_accomplishment_path, {class: "nav-link w-nav-link"} %>
            <%= link_to 'My Week', user_path(current_user), {class: "nav-link w-nav-link"} %>
            <%= link_to 'Today', today_path, {class: "nav-link w-nav-link"} %>
          <% else %>
            <%= link_to 'Sign Up', signup_path, {class: "nav-link w-nav-link"} %>
            <%= link_to 'Log In', login_path, {class: "nav-link w-nav-link"} %>
          <% end %>
        </nav>
      </div>
    </div>

    <div class="container">



      <% flash.each do |k, v| %>
        <%= content_tag :div, v, class: "flash-#{k}" %>
      <% end %>

      <%= yield %>



    </div>

    <div class="navbar">
      <div>
        <h3 class="heading">Once a week.</h3>
      </div>
    </div>

  </body>
</html>